// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Triton_Express_Vehicle_Tracker.Models;

namespace Triton_Express_Vehicle_Tracker.Migrations
{
    [DbContext(typeof(TritonExpressContext))]
    [Migration("20201105170628_vehiclemodel")]
    partial class vehiclemodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Triton_Express_Vehicle_Tracker.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Branch_Location")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Branch_Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Triton_Express_Vehicle_Tracker.Models.Vehicle", b =>
                {
                    b.Property<int>("Vehicle_Registration_Number")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Vehicle_Make")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Vehicle_Model")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Vehicle_Number_Plate")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Vehicle_Registration_Number");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
